name: custom-badges-dev

services:
    app:
      build:
        context: ..
        dockerfile: ./docker/Dockerfile.dev
      restart: unless-stopped
      volumes:
        - ../src:/app/src
        - ../logs:/app/logs

    db:
      image: postgres:latest
      restart: unless-stopped
      volumes:
        - db-data:/var/lib/postgresql/data
        - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
         
volumes:
  db-data: