CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.projects (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    code_coverage NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    token TEXT NOT NULL
);