services:
  app:
    environment:
      TZ: YOUR_TIMEZONE_HERE
      LOG_LEVEL: YOUR_LOG_LEVEL_HERE
      DB_USER: YOUR_DB_USERNAME_HERE
      DB_PASSWORD: YOUR_DB_PASSWORD_HERE
      DB_NAME: YOUR_DB_NAME_HERE
      CORS_WHITELIST: YOUR_COMMA_SEPARATED_LIST_OF_ALLOWED_DOMAINS_HERE
    ports:
      - "YOUR_EXTERNAL_PORT:80"

  db:
    environment:
      POSTGRES_USER: YOUR_DB_USERNAME_HERE
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD_HERE
      POSTGRES_DB: YOUR_DB_NAME_HERE
    ports:
      - "YOUR_EXTERNAL_PORT:5432"