name: custom-badges-dev

services:
  app:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
      - ../migrations:/app/migrations
      - ../public:/app/public
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL: false

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
